variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
trigger:
  branches:
    include:
    - main
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Maven@3
    displayName: Maven pom.xml
    inputs:
      mavenPOMFile: $(BuildParameters.mavenPOMFile)
      jdkVersion: 1.17
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**/*.jar'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy Azure App Service'
    inputs:
      azureSubscription: '$(Parameters.ConnectedServiceName)'
      appType: '$(Parameters.WebAppKind)'
      WebAppName: '$(Parameters.WebAppName)'
      packageForLinux: '$(System.DefaultWorkingDirectory)/_Lab Azure Cloud-Maven-CI (1)/drop/target/challenge-0.0.1-SNAPSHOT.jar'
